---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component downloads files from S3 by using S3 Transfer Manager."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
# TokenExchangeService is needed to get the credentials to access to the media S3 Bucket
  aws.greengrass.TokenExchangeService:
    VersionRequirement: '^2.0.3'
    DependencyType: HARD
ComponentConfiguration:
  DefaultConfiguration:
  # We must provide access to MQTT topics
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        aws.greengrass.labs.S3FileDownloader:mqttproxy:1:
          policyDescription: "Allows subscribe to mqtt topics."
          operations: 
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - "things/{iot:thingName}/download"
            - "things/{iot:thingName}/pause"
        aws.greengrass.labs.S3FileDownloader:mqttproxy:2:
          policyDescription: "Allows publish to mqtt topics."
          operations: 
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "things/{iot:thingName}/update"
    DOWNLOAD_TOPIC: "things/{iot:thingName}/download" # sends download command to S3FileDownloader
    PAUSE_TOPIC: "things/{iot:thingName}/pause" # sends pause command to S3FileDownloader
    JOB_FEEDBACK_TOPIC: "things/{iot:thingName}/update" # S3FileDownloader gives feedback for job updates
    DESTINATION_FOLDER: "/tmp/destination/" # This folder will be used to store media files in the local device
Manifests:
  - Platform:
      os: /linux|windows/
      architecture: /x86|aarch64|amd64|arm/
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/S3FileDownloader-1.0.0.jar"
    Lifecycle:
    # We need to create the destination folder if it doesn't exist
      Install: |
        mkdir -p {configuration:/DESTINATION_FOLDER}
      Run: "java -cp {artifacts:path}/S3FileDownloader-1.0.0.jar aws.greengrass.labs.S3FileDownloader.App {configuration:/DOWNLOAD_TOPIC} {configuration:/PAUSE_TOPIC} {configuration:/JOB_FEEDBACK_TOPIC} {configuration:/DESTINATION_FOLDER}"
